### ISSUE TITLE
Getting "TypeError: this.calendar.dateRange.start.split is not a function on my production server

### ISSUE THREAD

**Issue by SimonJ** [ManukMinasyan/vue-functional-calendar#117]
Hi,

Really like this package! Thanks a lot for that  🙏

I have a little issue when i on my production server run "yarn install" and "yarn production". Then am getting this error
<img width="1668" alt="Skærmbillede 2020-12-15 kl  22 55 00" src="https://user-images.githubusercontent.com/183790/102277578-c6b62680-3f28-11eb-92a1-01138ff14648.png">

But on my local enviroment it works fine and i do the same "yarn install" and i have tried with "yarn production" too. and it works fine. Do you guys know what can be wrong? am on version *2.8.79*

Node version on local and production: v14.9.0
npm version on local and production: 6.14.8

Really really wierd 🤔

**Comment by xlcrr** [comment]
Same error here when upgrading from 2.8

did you find a fix?

**Comment by ManukMinasyan** [comment]
Hello. Thanks for your feedback. Now I don't have time to deal with the calendar. Please create pull requests, I will appreciate it, it will be useful for the community.
